Parameters:
  EnvironmentName:
    Description: An environment name
    Type: String

  VPC:
    Type: AWS::EC2::VPC::Id
    Description: Choose VPC

  Subnets:
    Description: Choose Subnets
    Type: List<AWS::EC2::Subnet::Id>

  SecurityGroup:
    Description: Select Security Group
    Type: AWS::EC2::SecurityGroup::Id
# Create LB
Resources:
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Ref EnvironmentName
      Subnets: !Ref Subnets
      SecurityGroups:
        - !Ref SecurityGroup
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName
# Config LB Listener
  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref DefaultTargetGroup
# Map LB to VPC
  DefaultTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${EnvironmentName}-default
      VpcId: !Ref VPC
      Port: 80
      Protocol: HTTP